<?php

namespace Src\Controllers;

use Sober\Controller\Controller;

class PageCareers extends Controller
{


    public function __construct()
    {


    }

    public function __before()
    {

        parent::__before(); // TODO: Change the autogenerated stub

    }

    public function careers()
    {

        return self::get_posts();

    }

    public function career_categories()
    {
        $career_terms = get_terms([
            'taxonomy' => 'department',
            'include_children' => false
        ]);

        return $career_terms;
    }

    private function get_posts()
    {

        $posts = get_posts([
            'orderby'          => 'date',
            'order'            => 'DESC',
            'post_type'        => 'career',
            'numberposts'      => -1,
        ]);

        return self::format_posts($posts);

    }

    private function format_posts($posts)
    {
        $formatted_posts = [];

        foreach ($posts as $post) {

            $formatted_posts[] = [
                'title' => get_the_title($post->ID),
                'link' => get_permalink($post->ID),
                'job_type' => get_field('job_type', $post->ID),
                'start_date' => get_field('start_date', $post->ID),
                'excerpt' => get_the_excerpt($post->ID),
                'category_name' => self::get_career_post_term_names($post->ID),
                'category_slug' => self::get_career_post_term_slugs($post->ID),
                'post_date' => self::careers_convert_to_time_ago(get_the_date('d F Y', $post->ID))
            ];
        }

        return $formatted_posts;

    }

    private function get_career_post_term_names($post_id)
    {
        $terms = wp_get_post_terms($post_id, 'department');

        $format_terms = [];

        foreach ($terms as $term) {
            $format_terms[] = $term->name;
        }

        return $format_terms;
    }

    private function get_career_post_term_slugs($post_id)
    {
        $terms = wp_get_post_terms($post_id, 'department');

        $format_terms = [];

        foreach ($terms as $term) {
            $format_terms[] = $term->slug;
        }

        return $format_terms;
    }

    private function careers_convert_to_time_ago($original_time)
    {
        $original_time = strtotime($original_time);
        return human_time_diff( $original_time, current_time( 'timestamp' ) ).' '.__( 'ago' );
    }

}
