<?php

namespace Src\Controllers;

use Src\Classes\HomeBanner;
use Src\Classes\HeaderBanner;
use Sober\Controller\Controller;
use Src\Controllers\PageServices;
use Src\Controllers\Partials\SaveSession;

class App extends Controller
{

    use SaveSession;
    use Partials\AllClients;
    use Partials\AllAwards;
    use Partials\AllTeamMembers;
    use Partials\AllTestimonials;
    use Partials\LatestCaseStudies;
    use Partials\RelatedPosts;

    public function __construct()
    {


    }

    public function __before()
    {

        parent::__before(); // TODO: Change the autogenerated stub

    }

    public function siteName()
    {

        return get_bloginfo('name');

    }

    public static function title()
    {

        if (is_archive()) {
            return get_the_archive_title();
        }
        if (is_search()) {
            return sprintf(__('Search Results for %s', 'sage'), get_search_query());
        }
        if (is_404()) {
            return __('Not Found', 'sage');
        }


        return get_the_title();

    }

    // ALIASES

    public function banner()
    {

        if (is_front_page()) {
            return (new HomeBanner(get_the_ID()))->render();
        } else {
            return (new HeaderBanner(get_the_ID()))->render();
        }

    }

    public function industries()
    {
        if (is_front_page()) {
            return (new PageServices())->industries();
        }
    }

    public function fields()
    {

        return get_fields(get_the_ID());

    }

    public function career_fields() {

        return get_fields(1530);

    }

    public function contact_fields() {

        return get_fields(25);

    }

    public function pagination()
    {

        return \App\sage('pagination')->pagination('', 4);

    }

}
