<?php

namespace Src\Controllers;

use Sober\Controller\Controller;

class PageServices extends Controller
{


    public function __construct()
    {


    }

    public function __before()
    {

        parent::__before(); // TODO: Change the autogenerated stub

    }

    public function services()
    {

        return self::get_posts('service');

    }

    public function industries()
    {

        return self::get_posts('industry');

    }

    private function get_posts($type)
    {

        $posts = get_posts([
            'numberposts'      => -1,
            'orderby'          => 'menu_order',
            'order'            => 'ASC',
            'post_type'        => 'services',
            'suppress_filters' => true,
            'tax_query' => [
                [
                    'taxonomy' => 'service_type',
                    'field' => 'slug',
                    'terms' => $type,
                    'operator' => 'IN',
                ]
            ]
        ]);

        return self::format_posts($posts);

    }

    private function format_posts($posts)
    {

        $formatted_posts = [];

        foreach ($posts as $post) {

            $image = get_field('service_listing_image', $post->ID);

            $formatted_posts[] = [
                'title' => get_the_title($post->ID),
                'link' => get_permalink($post->ID),
                'image' => ($image == "") ? 'https://placehold.it/768x768' : $image['sizes']['service_tile'],
                'content' => get_field('service_listing_content', $post->ID)
            ];

        }

        return $formatted_posts;

    }

}
